### ISSUE TITLE
Please add quickstart

### ISSUE THREAD

**Issue by avloss** [garden-io/go3dprint#6]
```
$ kubectl apply -f garden.yml
error: SchemaError(io.k8s.api.apps.v1beta2.DaemonSetStatus): invalid object doesn't have additional properties
```
can't start command with `minikube`, please advice on how to start correctly, or if there are any dependencies which should be installed!

**Comment by ellenkorbes** [comment]
Sorry about that. To start you should use Garden itself, e.g. `garden dev` on the project root.

To enable hot reload use `garden dev --hot=mesh`.
